version: "3.8"
services: 
    scrapy:
        container_name: scrapy
        image: scrapy:latest
        volumes: 
            - ./:/app/
        working_dir: /app/webemail/scrapemail
        # command: ["sleep","1000"]
        command: ["scrapy","crawl","collectemail","-o","samplemail.csv"]